CEXT-2009 Add New Relic support to aio CLI
adobe/aio-cli-plugin-runtime pull request #311
Opened 2023-06-28 10:09 UTC by gjmarques

## Description
Add New Relic support to log forwarding

## Related Issue
#310 

## Motivation and Context
Log Forwarding currently supports Splunk and Azure Log Analytics. This PR adds support for New Relic.

## How Has This Been Tested?
Auto tests are included

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-28 13:17 UTC, pablomoreno61 approved these changes

2023-06-28 13:32 UTC, aminakhyat approved these changes

2023-06-29 19:51 UTC, buskamuza requested changes

2023-06-29 19:51 UTC, buskamuza commented on test/commands/runtime/namespace/log-forwarding/set.test.js
> +    license_key: 'key1'
Can we add a test with no license test provided as it's an optional argument?

2023-07-06 02:53 UTC, shazron commented
@gjmarques:
1. Does this PR depends on https://github.com/adobe/aio-lib-runtime/pull/148  being released?
2. The tests have failures, can you please check.

2023-07-06 09:54 UTC, gjmarques commented
@shazron 
Yes this PR depends on https://github.com/adobe/aio-lib-runtime/pull/148
Tests should be fixed

2023-07-13 14:33 UTC, buskamuza approved these changes

2023-07-13 15:32 UTC, shazron approved these changes

2023-07-17 15:15 UTC, merged